# This file will be picked up under the following locations
# /etc/scarab/scarab.yml
# ~/.config/scarab/scarab.yml
# ~/.scarab/config/scarab.yml
# ~/.scarab.yml

scarab:
  profiles:
    # required, the argument to pass to the "profile"-command
    - profile: myProfile

      # required, "create" or "update"
      mode: create

      # required, absolute paths, "~" will be expanded)
      source: /source/path
      target: /target/path

      # required, name-format 1..6
      name: 5

      # optional, default false
      ignore_datetime: true
